DROP TABLE IF EXISTS APP_USERS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS ADDRESSES;
DROP TABLE IF EXISTS NOTIFICATION_PREFERENCES;


CREATE TABLE IF NOT EXISTS APP_USERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS CUSTOMERS (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ADDRESSES (
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    TYPE VARCHAR(10) NOT NULL,
    ADDRESS_VALUE VARCHAR(255) NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

CREATE TABLE IF NOT EXISTS NOTIFICATION_PREFERENCES (
    ID SERIAL PRIMARY KEY,
    CUSTOMER_ID BIGINT NOT NULL,
    OPT_IN_SMS BOOLEAN NOT NULL,
    OPT_IN_EMAIL BOOLEAN NOT NULL,
    OPT_IN_PROMOTIONAL_MESSAGES BOOLEAN NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(ID)
);

